version: '3'

services:
    redis:
        image: redis:latest
        container_name: redis.redisratelimiting.docker
        restart: unless-stopped
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379
        networks:
            - global
networks:
    global:
        external: true